# Generated by Django 4.2.4 on 2023-08-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripscan',
            name='longitude',
            field=models.TextField(default='123456'),
            preserve_default=False,
        ),
    ]
