# Generated by Django 4.2.4 on 2023-08-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_member_uuid_alter_organization_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'admin'), ('HR', 'HR'), ('member', 'member')], max_length=15),
        ),
    ]
