# Generated by Django 4.2.4 on 2023-08-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_alter_role_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.role'),
        ),
    ]
