# Generated by Django 4.2.4 on 2023-08-10 05:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tripscan', '0001_initial'),
        ('roles', '0002_alter_member_uuid_alter_organization_uuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_location', models.JSONField()),
                ('end_location', models.JSONField()),
                ('status', models.CharField(choices=[('created', 'created'), ('started', 'started'), ('ended', 'ended')], max_length=15)),
                ('trip_type', models.CharField(choices=[('self', 'self'), ('assigned', 'assigned')], max_length=10)),
                ('priority', models.CharField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.member')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TripDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('end_scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tripscan_end', to='tripscan.tripscan')),
                ('start_scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tripscan_start', to='tripscan.tripscan')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
        ),
    ]
