# Generated by Django 4.2.4 on 2023-08-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip_detail', to='trips.trip'),
        ),
    ]
