# Generated by Django 4.2.4 on 2023-08-11 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_tripdetails_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('urgent', 'urgent')], max_length=18),
        ),
    ]
