# Generated by Django 4.2.4 on 2023-08-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='default', max_length=245),
            preserve_default=False,
        ),
    ]
